alibaba/designable

packages/react-settings-form/src/SettingsForm.tsx

Signed-off-by: dark <dark.lijin@gmail.com>

refactor(settings): rename idleReuqest to idleRequest

---

packages/playground/src/main.tsx

fix: playground text fix.

---

packages/core/src/models/Dragon.ts
packages/core/src/models/Operation.ts

Signed-off-by: dark <dark.lijin@gmail.com>

fix(core): fix typo

---

packages/react-settings-form/src/SettingsForm.tsx
packages/react-settings-form/src/types.ts

refactor(settings): expose setting form's scope property

---

packages/core/package.json
packages/core/tsconfig.build.json
packages/core/tsconfig.json
packages/formily/package.json
packages/formily/tsconfig.build.json
packages/formily/tsconfig.json
packages/playground/tsconfig.build.json
packages/playground/tsconfig.json
packages/react-sandbox/package.json
packages/react-sandbox/tsconfig.build.json
packages/react-sandbox/tsconfig.json
packages/react-settings-form/package.json
packages/react-settings-form/tsconfig.build.json
packages/react-settings-form/tsconfig.json
packages/react/package.json
packages/react/tsconfig.build.json
packages/react/tsconfig.json
packages/shared/package.json
packages/shared/tsconfig.build.json
packages/shared/tsconfig.json
tsconfig.json

chore(ts): map @designable/* to src folder during development

---

packages/formily/README.md

docs(readme): fix content

---

packages/react/src/widgets/ComponentTreeWidget/index.tsx

This happens when the `react-refresh` accepts the updates.

fix(react): tree maybe undefined

---

packages/react/src/panels/styles.less

fix(react): remove duplicate css properties

---

packages/shared/src/event.ts
packages/shared/src/index.ts
packages/shared/src/subscribable.ts

Update the misspell word from 'subscrible' to 'subscribable'.

fix(shared): misspell for subscribable

---

packages/core/src/models/Dragon.ts
packages/core/src/models/Hover.ts
packages/core/src/models/TreeNode.ts
packages/core/src/models/Viewport.ts

fix(core): remove unused this optional chain

---

package.json

chore: fix repository url

---

formily/antd/src/components/ArrayCards/preview.tsx
formily/antd/src/components/ArrayTable/preview.tsx
formily/next/src/components/ArrayCards/preview.tsx
formily/next/src/components/ArrayTable/preview.tsx

formily升级到2.0.0-rc.19后，ArrayBase.Item需要添加record属性

fix(react): fix missing record props in ArrayBase.Item

---

packages/react-settings-form/src/components/BoxShadowStyleSetter/index.tsx
packages/react-settings-form/src/components/BoxStyleSetter/index.tsx

feat(react-settings-form): update SizeInput

---

formily/setters/src/components/DataSourceSetter/TreePanel.tsx

fix two bug for `DataSourceSetter`:
- With initialKeyValuePairs, linkage error.
- Cannot drag node.

fix(setter): initial bug

---

formily/antd/playground/widgets/MarkupSchemaWidget.tsx
formily/next/playground/widgets/MarkupSchemaWidget.tsx

fix(antd/next): Text component echo

---

packages/react/src/panels/StudioPanel.tsx

fix(react): fix studiopanel className setting

---

packages/react/src/panels/StudioPanel.tsx

fix(react): fix position props in StudioPanel

---

packages/react/src/widgets/IconWidget/index.tsx

fix(react): create attach-shadow repeatedly

---

examples/basic/src/main.tsx
examples/sandbox/src/main.tsx
formily/antd/playground/widgets/ActionsWidget.tsx
formily/next/playground/widgets/ActionsWidget.tsx

Automatically sets the current language to simplified Chinese when the browser's configuration language does not match in multiple languages

fix(formily): Set default language

---

packages/shared/src/event.ts

fix(shared/event): Infinite recursion

---

formily/antd/src/components/FormGrid/preview.tsx

fix: fix bug formgrid设置最大列小于总网格列出现卡死,发现totalColumns计算值重复导致

---

packages/core/src/drivers/KeyboardDriver.ts

fix(core): fix web components compatibility in KeyboardDriver

---

packages/react/src/widgets/IconWidget/index.tsx

https://github.com/alibaba/designable/issues/204

fix(react): #204

---

formily/setters/src/components/DataSourceSetter/styles.less

use .@{ant-prefix} instead of .ant to fix the style problem.

fix(formily): fix antd style prefix problem in data source setter

---

packages/core/src/effects/useTranslateEffect.ts
packages/core/src/models/AlignLine.ts
packages/core/src/models/DragLine.ts
packages/core/src/models/TreeNode.ts
packages/react/src/widgets/AuxToolWidget/AlignLine.tsx
packages/shared/src/coordinate.ts

chore: improve align line drag experience

---

packages/core/src/shortcuts/QuickSelection.ts

An error occurs when press the ArrowUp on the keyboard on the root node

fix(core): quick selection error
